version: 2
jobs:
  deploy:
    steps:
      - checkout
      - deploy:
          name: heroku deploy
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
#workflows:
#  version: 2
#  build-deploy:
#    jobs:
#      - deploy:
#          filters:
#            branches:
#              only: master
