version: 2
jobs:
  build:
    docker:
      - image:  circleci/php:7.1.8-browsers
    steps:
      - checkout
      - deploy:
          name: heroku deploy
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

